INSERT INTO ACCOUNTS (ACCOUNT_OWNER, ACCOUNT_BALANCE) VALUES ('Santiago', 1000);
INSERT INTO ACCOUNTS (ACCOUNT_OWNER, ACCOUNT_BALANCE) VALUES ('John', 2000);

INSERT INTO BANKS (BANK_NAME, BANK_TOTAL_TRANSFERS) VALUES ('Bank of America', 0);
